name: CD - Develop

on: 
  push:
    branches:
      - develop
  schedule:
    - cron: '0 15 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 60
          browser: chrome
          record: true
          group: 'Back end - Tests'
          build: npm install
          start: npm run cypress:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}